### ISSUE TITLE
Ardupolit not working with mac

### ISSUE THREAD

**Issue by DroneRookie** [ArduPilot/apm_planner#1212]
Hello Experts,
I recently got a new drone which has ARDUPOLIT, I am not able to connect it with mission planner/APM2  in mac. I couldn't install APM in mac as it said version is not compatible with last Mac OS. Hence I then connect it with windows via virtual machine (parallel). But I am still not able to connect to mission planner.
I am not sure whether my ARDUPOLIT is not working or I am missing any part.
PLease help!!

**Comment by billbonney** [comment]
see https://github.com/ArduPilot/apm_planner/releases for latest release that has been tested on macOS Catalina 10.15.5

**Comment by DroneRookie** [comment]
Hello Billbonney, 
Thanks for your reply but as you may have guessed i am new to all this, from above link how do i install ardupilot in mac.when i tried it gave me same error again "not compatible with macOS Catalina.
Any help will be greatly appreciated.

**Comment by billbonney** [comment]
if you CTRL-CLICK and then select OPEN it should open. The only error message should be 'unidentified developer' as it's not a 'signed package'

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

if that's not the case, can you post a screen grab of the error message. It is working for me and I tested on a clean machine.

**Comment by DroneRookie** [comment]
I am already doing that , i am aware of CTRL-CLICK functionality but i am still getting below error.
I have attached all the relevant SS while installing APM planner.

<img width="649" alt="Screenshot 2020-06-16 at 12 37 33" src="https://user-images.githubusercontent.com/66937438/84769770-4b51d780-afce-11ea-9e63-e84a992c8e0b.png">
<img width="719" alt="Screenshot 2020-06-16 at 12 37 53" src="https://user-images.githubusercontent.com/66937438/84769776-4ee55e80-afce-11ea-869c-744047598269.png">
<img width="717" alt="Screenshot 2020-06-16 at 12 38 17" src="https://user-images.githubusercontent.com/66937438/84769780-51e04f00-afce-11ea-8cb6-085ff55b8e25.png">

<img width="683" alt="Screenshot 2020-06-16 at 12 35 29" src="https://user-images.githubusercontent.com/66937438/84769522-e26a5f80-afcd-11ea-9af5-18675f761587.png">

**Comment by billbonney** [comment]
You don’t need the FTDI serial port driver anymore. It’s built into macOS.

**Comment by DroneRookie** [comment]
Thanks for your reply.
I didn't exclusively download FTDI serial-orr drivers, its included in the APM installer.
Can you please tell me how do i go about it then?

**Comment by billbonney** [comment]
Just drag ‘APM Planner 2.0’ to the Applications folder on your machine and Open it

**Comment by DroneRookie** [comment]
Thanks Billbonney,
I could install APM now ( one step done:))
But now when i plugin  my ARDUPOLIT to the laptop and try to install firmware i am getting below error "No valid device found.Chk to be sure your APM2.5+ or  PIXHAWK/PX4 is plugged in and drivers installed"
<img width="1065" alt="Screenshot 2020-06-16 at 18 41 59" src="https://user-images.githubusercontent.com/66937438/84808973-57a35800-b001-11ea-984d-bfbffbebffaf.png">

**Comment by mboland** [comment]
I had similar issues some time ago (years) and did an uninstall and haven’t had issues since.
From the FTDI website you can find their driver manuals which are helpful:

4.2 Uninstalling FTDI VCP Drivers on OS X 10.9 onwards
To remove the drivers from Mac OS X 10.9 onwards, the user must be logged on as root. Root is a reserved username that has the privileges required to access all files.
Start a Terminal session (Go > Applications > Utilities > Terminal) and enter the following commands at the command prompt:
cd /Library/Extensions
rm -r FTDIUSBSerialDriver.kext
then reboot
To temporarily operate as the root user you can use sudo at the beginning of the command e.g.
cd /Library/Extensions
sudo rm -r FTDIUSBSerialDriver.kext
then reboot
The driver will then be removed from the system.

4.3 Uninstalling D2XX Drivers
To uninstall the D2XX driver, simply delete the library and the symbolic link: Start a Terminal session (Go > Applications > Utilities > Terminal)
Change directory to the /usr/local/lib (cd /usr/local/lib)
Delete the library (rm libftd2xx.1.2.2.dylib)
Delete the symbolic link (rm libftd2xx.dylib)
If you have installed D2xxHelper (required for OS X 10.11 onwards), it also must be removed:
sudo rm –r /Library/Extensions/D2xxHelper.kext
Complete the uninstallation by rebooting.

Hope this helps.

**Comment by DroneRookie** [comment]
Hello Mboland,
Thanks for your reply.
I have uninstalled above drivers as you had said but still no luck. I am still getting error "No valid device found"
Do i need to install the drivers back from their website or as Billbonney said, new version has these drivers inbuilt.

**Comment by mboland** [comment]
Install the NEW version from their website.
Also don’t rely on the USB cables you are using.

**Comment by DroneRookie** [comment]
Sorry still not working, installed new drivers and changes USB cable as well.

**Comment by DroneRookie** [comment]
Guys, one more step done, one more step conquered.
Now i am able to connect to APM planner and its able to find port as well.
I  tried to install firmware for quadcopter, it got completed saying "APM flashing complete".
Unfortunately that's as far as i could go. Nothing happens after that.
Am I missing anything after that , do i need to do anything else to start my configuration.
I clicked on connect and screen is shown connected but there is no movement on the left side panel.

**Comment by Arne-W** [comment]
You should use the [support forum](https://discuss.ardupilot.org/c/ground-control-software/apm-planner-2-0/72)... however in your home directory the should be a folder named apmplanner2. Within that folder you should find logfiles. Take a look - perhaps they can help to find out whats going wrong.
